### ISSUE TITLE
Please implement the support of Vaadin 8

### ISSUE THREAD

**Issue by igorbljahhin** [tehapo/WizardsForVaadin#21]
or at least support of Vaadin 8 compatibility library.

Thank you in advance!

**Comment by tehapo** [comment]
Unfortunately I currently don't have time to maintain this add-on. But if someone wants to work on this, I'm happy to review a pull request. 😉

**Comment by igorbljahhin** [comment]
That was my plan. Fix is ready, but what version number should I use? 1.1.2 is not very wise, maybe 8.0.0?

**Comment by tehapo** [comment]
Cool! 👍  Don't worry about the version number. I'll come up with a new version tag after I have merged the pull request. 😄
