### ISSUE TITLE
Wizard v2.x: References to vaadin V7

### ISSUE THREAD

**Issue by HSorensen** [tehapo/WizardsForVaadin#25]
When using the Wizard add-on I receive this message inside the browser when running the app:
`Widgetset 'com.vaadin.DefaultWidgetSet' does not contain an implementation for com.vaadin.v7.ui.Label. Check the connector's @Connect mapping, the widgetset's GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to add-on instructions. `

Can the com.vaadin.v7 references be changed to the newest variants ?

**Comment by HSorensen** [comment]
I created pull request #26  with suggested changes.

**Comment by tehapo** [comment]
Merged the PR #26.
